//! The Project Model — Lunar's owned source of truth for the open project.
//!
//! Today this is deliberately small: the root path and the project's name
//! (read from `default.project.json`). It exists so the rest of the app stops
//! passing a bare `path: String` around and instead queries a real model that
//! later phases grow — the parsed DataModel/sourcemap tree (0.2), the
//! per-project manifest (0.3), the dependency graph and runtime state beyond.
//!
//! The model lives here, in the backend, as Tauri-managed state. The frontend
//! sees immutable snapshots over commands and is told to refetch via events.

use std::path::{Path, PathBuf};
use std::sync::Mutex;

use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Emitter, State};

/// The Rojo project file we look at to name the project. Phase 0.3 will let the
/// per-project manifest override this; for now it is the Rojo default.
const DEFAULT_PROJECT_FILE: &str = "default.project.json";

/// The sourcemap Lunar owns. Generated by our own `rojo sourcemap --watch` (see
/// the frontend `use-sourcemap` hook) and parsed here into the DataModel tree.
/// Phase 0.3's manifest will let this be overridden; for now it is the default.
const SOURCEMAP_FILE: &str = "sourcemap.json";

/// The subset of `*.project.json` we currently parse. The `tree` is left opaque
/// until 0.2 builds the DataModel from the generated sourcemap.
#[derive(Debug, Deserialize)]
struct RojoProjectFile {
    name: String,
}

/// The in-memory model for the currently open project.
#[derive(Debug, Clone)]
pub struct ProjectModel {
    root: PathBuf,
    name: String,
    project_file: String,
}

impl ProjectModel {
    /// Build the model for a freshly opened folder. Reading the project file is
    /// best-effort: opening a plain folder (no Rojo project) is valid, so we
    /// fall back to the folder's own name rather than failing.
    fn load(root: &Path) -> Self {
        let project_file = DEFAULT_PROJECT_FILE.to_string();
        let name = std::fs::read_to_string(root.join(&project_file))
            .ok()
            .and_then(|text| serde_json::from_str::<RojoProjectFile>(&text).ok())
            .map(|project| project.name)
            .unwrap_or_else(|| folder_name(root));

        ProjectModel {
            root: root.to_path_buf(),
            name,
            project_file,
        }
    }

    fn snapshot(&self) -> ProjectSnapshot {
        ProjectSnapshot {
            root: self.root.to_string_lossy().into_owned(),
            name: self.name.clone(),
            project_file: self.project_file.clone(),
        }
    }
}

/// The immutable view of the model that crosses to the frontend.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProjectSnapshot {
    pub root: String,
    pub name: String,
    pub project_file: String,
}

/// A node in the Rojo sourcemap — an instance in the DataModel mapped to the
/// file(s) that produce it. Mirrors the on-disk `sourcemap.json` shape, which is
/// also what we hand back to the frontend (hence camelCase both ways).
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DataModelNode {
    pub name: String,
    pub class_name: String,
    #[serde(default)]
    pub file_paths: Vec<String>,
    #[serde(default)]
    pub children: Vec<DataModelNode>,
}

/// Tauri-managed holder for the single open project (or none on the home screen).
#[derive(Default)]
pub struct ProjectStore(Mutex<Option<ProjectModel>>);

/// Open `root` as the active project, replacing any previous one. Returns the
/// snapshot directly (so the caller needn't round-trip an event) and also emits
/// `project://opened` for any other listeners.
#[tauri::command]
pub fn project_open(
    app: AppHandle,
    store: State<'_, ProjectStore>,
    root: String,
) -> ProjectSnapshot {
    let model = ProjectModel::load(Path::new(&root));
    let snapshot = model.snapshot();
    *store.0.lock().unwrap() = Some(model);
    let _ = app.emit("project://opened", snapshot.clone());
    snapshot
}

/// Clear the active project (returning to the home screen).
#[tauri::command]
pub fn project_close(app: AppHandle, store: State<'_, ProjectStore>) {
    *store.0.lock().unwrap() = None;
    let _ = app.emit("project://closed", ());
}

/// Current project snapshot, or `null` when none is open.
#[tauri::command]
pub fn project_snapshot(store: State<'_, ProjectStore>) -> Option<ProjectSnapshot> {
    store.0.lock().unwrap().as_ref().map(ProjectModel::snapshot)
}

/// The parsed DataModel tree for the open project, or `null` when no project is
/// open or no sourcemap has been generated yet. Parsed lazily from the on-disk
/// `sourcemap.json` that Lunar keeps fresh, so callers always get current data;
/// a later phase can cache it and push `project://changed` on regeneration.
#[tauri::command]
pub fn project_data_model(store: State<'_, ProjectStore>) -> Option<DataModelNode> {
    let root = store.0.lock().unwrap().as_ref().map(|model| model.root.clone())?;
    let text = std::fs::read_to_string(root.join(SOURCEMAP_FILE)).ok()?;
    serde_json::from_str(&text).ok()
}

fn folder_name(root: &Path) -> String {
    root.file_name()
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_else(|| "project".to_string())
}
